export const suggestions = [
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Soins',
        value: 'sce',
        name: "Soin Coup d'éclat",
        price: 29.90,
        duration: 30,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Soins',
        value: 'shn',
        name: "Soin Hydratant et Nourrissant",
        price: 39,
        duration: 45,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Soins',
        value: 'st',
        name: "Soin Traitant",
        price: 59,
        duration: 90,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Soins',
        value: 'saa',
        name: "Soin Anti-Age",
        price: 75,
        duration: 10,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Soins',
        value: 'ct',
        name: "Cryothérapie",
        price: 39.90,
        duration: 60,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Massages',
        value: 'mk',
        name: "Massage Kobido",
        price: 40,
        duration: 60,
        path: "/massages.html?target=mk",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Massages',
        value: 'mks',
        name: "Massage Kobido Suprême",
        price: 54,
        duration: 80,
        path: "/massages.html?target=mks",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Massages',
        value: 'mbr',
        name: "Massage Beauté du Regard",
        price: 40,
        duration: 60,
        path: "/massages.html?target=mbr",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Massages',
        value: 'mc',
        name: "Massage Californien",
        price: 45,
        duration: 60,
        path: "/massages.html?target=mc",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Massages',
        value: 'gm',
        name: "Gommage et Massage",
        price: 40,
        duration: 60,
        path: "/massages.html?target=gm",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'evl',
        name: "Lèvres",
        price: 8.50,
        duration: 10,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'evm',
        name: "Menton",
        price: 8.50,
        duration: 10,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'evj',
        name: "Joues",
        price: 9,
        duration: 10,
        path: "/"
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'evc',
        name: "Visage (Sourcils + Lèvres + Menton)",
        price: 21,
        duration: 45,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'esl',
        name: "Création ligne sourcils",
        price: 12,
        duration: 10,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'ees',
        name: "Sourcils",
        price: 9,
        duration: 10,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'ec',
        name: 'Cou',
        price: 9,
        duration: 10,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'ev',
        name: 'Ventre',
        price: 9,
        duration: 10,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'ejc',
        name: 'Jambes Complètes',
        price: 25,
        duration: 45,
        path: "/", // NOTICED THAT IT SEEMS LONG!!
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'edj',
        name: '1/2 Jambes',
        price: 18,
        duration: 20,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'etqj',
        name: '3/4 Jambes',
        price: 22,
        duration: 25,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'ej',
        name: 'Cuisses',
        price: 18,
        duration: 20,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'eme',
        name: "Maillot Échancré",
        price: 16,
        duration: 25,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'emsi',
        name: 'Maillot Semi-Intégral',
        price: 22,
        duration: 25,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'emi',
        name: 'Maillot Intégral',
        price: 27,
        duration: 60,
        path: "/", // NOTICED THAT IT SEENS LONG!!
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'ea',
        name: 'Aisselles',
        price: 11,
        duration: 15,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'ebd',
        name: '1/2 Bras',
        price: 18,
        duration: 20,
        price: 12,
        duration: 15,
        path: "/",
    },
    {
        img: 'https://placehold.co/400',
        alt: 'placeholder image',
        group: 'Épilations',
        value: 'ebc',
        name: 'bras',
        price: 18,
        duration: 25,
        path: "/",
    },
    
]




